[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  RUBY_VERSION = "2.6.2"
  NODE_VERSION = "14.12.0"
# [[redirects]]
#   from = "https://www.fsconsults.com/"
#   to = "https://www.launchconsulting.com/future-state"
#  status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/about"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/talent"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/companies"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/dei"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/about/"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/talent/"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/companies/"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
# [[redirects]]
#   from = "https://www.fsconsults.com/dei/"
#   to = "https://www.launchconsulting.com/future-state"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
